version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: build/Dockerfile
    command: /app/bin/api
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ..
      dockerfile: build/Dockerfile
    command: /app/bin/worker
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

  listener:
    build:
      context: ..
      dockerfile: build/Dockerfile
    command: /app/bin/listener
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

  redis:
    image: "redis:latest"
    env_file:
      - .env.docker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: "redislabs/redisinsight:latest"
    env_file:
      - .env.docker
    ports:
      - "8001:8001"
    depends_on:
      - redis

  postgres:
    image: "postgres:17"
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dozzle:
    image: "amir20/dozzle:latest"
    env_file:
      - .env.docker
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data:
  postgres_data:
